# Generated by Django 3.1.3 on 2020-11-16 09:44

import uuid

import django.db.models.deletion
from django.db import migrations, models

import app.verify.models
import common.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Когда создан')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Когда изменён')),
                ('name', models.CharField(blank=True, max_length=4096, verbose_name='Наименование')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный идентификатор')),
                ('upload_file', models.FileField(upload_to=app.verify.models.get_upload_path, verbose_name='Эксель таблица с email')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Verify',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Когда создан')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Когда изменён')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный идентификатор')),
                ('email', models.EmailField(max_length=512, verbose_name='Проверяемый email')),
                ('result_code', models.PositiveSmallIntegerField(choices=[(1, 'Ok'), (2, 'Catch All'), (3, 'Unknown'), (4, 'Error'), (5, 'Disposable'), (6, 'Invalid')])),
                ('file', common.fields.UidForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='verify.file', verbose_name='Таблица с email')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
